typography_spectrum: 0.8457013524603099
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38820928055793047
  lightness: 0.7934342450462282
  saturation: 0.39092959999106824
  rhythmicContrast: 0.409504106733948
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.47998569649644196
analytics:
  google: null
  facebook: null
  twitter: null
name: Bihzhu
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
